[package]
name = "quika"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
cpal = "0.15.2"
ringbuf = "0.2.2"
spectrum-analyzer = "1.2.6"
rand = "0.8.5"